### ISSUE TITLE
User defined setting not overridding default settings

### ISSUE THREAD

**Issue by ing200086** [francodacosta/composer-sublime#10]
I use Windows 7 and have my composer globally installed to only require "composer".

I've tried to update ("composer_command":  "./composer.phar") to ("composer_command":  "composer") in the user defined settings, but the sublime terminal is still showing the original composer command. I tried to change a few other settings. None of the changes I made seemed to affect the package settings.

**Comment by francodacosta** [comment]
can you paste the full output of ST console?

**Comment by ing200086** [comment]
I tried it again and it is now working. Sublime text required a restart. Thank you!
