### ISSUE TITLE
How to use on Windows?

### ISSUE THREAD

**Issue by mabasic** [francodacosta/composer-sublime#8]
I get this error: `maximum recursion depth exceeded while calling a Python object` when I set the `composer_command` to point to my **composer.phar**

Any help?

**Comment by francodacosta** [comment]
@mabasic can you paste the output of the ST console, the trace log would be very helpful ?

**Comment by mabasic** [comment]
Hi,

this is the output I get:

```

 -- COMPOSER -- 

executing: ./composer.phar validate -n -v
'.' is not recognized as an internal or external command,

operable program or batch file.


-- Terminated -- 
```

And this is my user package preference:

```
{
    "composer_command":  "C:/ProgramData/ComposerSetup/bin/composer.phar",
}
```

**Comment by francodacosta** [comment]
Please go to "view -> show console", you should have more information there

**Comment by mabasic** [comment]
It's almost the same output:

```
 -- COMPOSER -- 


creating output panel
['./composer.phar', 'validate', '-n', '-v']
Skipping status bar messages
['./composer.phar', 'validate', '-n', '-v']
writting data
executing: ./composer.phar validate -n -v

process created
writting data
'.' is not recognized as an internal or external command,

operable program or batch file.



writting data

-- Terminated -- 


```

**Comment by mabasic** [comment]
Any help? Am i doing something wrong?

**Comment by wdmtech** [comment]
@mabasic - use:

"composer_command":  "composer"

As long as you have used the composer windows installer and composer is on your %PATH% then you should be golden :)

---

I also had to remove and re-install the plugin to get it to use my composer-sublime.sublime-settings

**Comment by mabasic** [comment]
Ok, I have followed your advice and now I get this:

```
 -- COMPOSER -- 


creating output panel
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "composer_st3 in C:\Users\Mario\AppData\Roaming\Sublime Text 3\Installed Packages\Composer.sublime-package", line 122, in run
  File "composer_st3 in C:\Users\Mario\AppData\Roaming\Sublime Text 3\Installed Packages\Composer.sublime-package", line 72, in go
  File "composer_st3 in C:\Users\Mario\AppData\Roaming\Sublime Text 3\Installed Packages\Composer.sublime-package", line 47, in prepareCommandList
TypeError: object of type 'NoneType' has no len()
```

Any idea?

**Comment by wdmtech** [comment]
Have you used the Windows Composer installer? You'll need composer on your Windows path in order to load it this way.

**Comment by mabasic** [comment]
Yes, I have installed it using a Composer installer and it is in Windows path. I can use it on  command line.

**Comment by wdmtech** [comment]
My composer-sublime.sublime-settings:

{

```
// show debug messages?
"show_debug": false,

// Show messages / progress in status bar?
"show_status": true,

// shows the output of composer ?
// if you disable it you get no information about composer progress (or even errors)
"show_output": true,

/*
 * Path to composer binary.
 * A relative path is relative to the composer.json file
 */
"composer_command":  "composer",

// Extra arguments for composer install command
"composer_install_extra" : ["-n", "-v"],

// Extra arguments for composer update command
"composer_update_extra" : ["-n", "-v"],

// Extra arguments for composer self-update command
"composer_selfupdate_extra" : ["-n", "-v"],

// Extra arguments for composer dump-autoload command
"composer_validate_extra" : ["-n", "-v"],

// Extra arguments for composer require command
"composer_require_extra" : ["-n", "-v"],

// Extra arguments for composer dump-autoload command
"composer_dumpautoload_extra" : ["-n", "-v"]
```

}

Try adding these and reinstall the plugin - I basically copied the entire default settings file and then modified "composer_command". If this doesn't work I'm not sure what will!

**Comment by mabasic** [comment]
Yeah, I don't know what to say. I just started sublime and run composer self update command and  it  worked. I changed nothing from the last time. Let's just close this issue :)

**Comment by kiwina** [comment]
Just like he mentioned! he probably didn't restart sublime after changing the setting
